name: 'safecd-sync'
description: 'Reconcile git and safes'
inputs:
  command:
    description: 'Command to run'
    required: true
  rpc:
    description: 'Ethereum RPC url'
    required: false
  users:
    description: 'Users to send reminders to'
    required: false
outputs:
  hasChanges:
    description: "Wether some changes occured during sync"
  hasPrComment:
    description: "Wether a PR comment was generated"
  hasFailedProposals:
    description: "Wether simulated proposals failed"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CI: true
    COMMAND: ${{ inputs.command }}
    RPC: ${{ inputs.rpc }}
    USERS: ${{ inputs.users }}