name: 'safecd-reminders'
description: 'Send reminder notifications to safe owners'
inputs:
  users:
    description: 'Users input for reminders'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: "node /app/dist/index.js reminders"
  env:
    CI: true
    USERS: ${{ inputs.users }}